const VIENSOI_APP = {
    "ACTIVE_FIXED_HEADER": true,
    "ACTIVE_HEADER_POSITION": 1,
    "ACTIVE_PADDING_MAIN": false,
    "ACTIVE_FIXED_FOOTER": true,
    "ACTIVE_RESPONSIVE": true,
    "ACTIVE_OFFCANVAS": true,
    "ACTIVE_BACKTOTOP": true,
    "DISPLAY_BACKTOTOP": 100,
    "CHANGE_GRID": 991
}