const VIENSOI_APP = {
    "ACTIVE_FIXED_HEADER": true,
    "HEADER_TRANPARENT": false,
    "ACTIVE_HEADER_POSITION": 1,
    "ACTIVE_PADDING_MAIN": true,
    "ACTIVE_FIXED_FOOTER": true,
    "DISPLAY_FOOTER": 600,
    "ACTIVE_RESPONSIVE": true,
    "ACTIVE_OFFCANVAS": false,
    "ACTIVE_BACKTOTOP": true,
    "DISPLAY_BACKTOTOP": 100,
    "CHANGE_GRID": 991,
    "DEV_MODE": true,
    "DEV_MODE_GIRD_FULL": false,
    "MEGA_MENU": false,
    "MEGA_MENU_COL": 5
}